version: 2
updates:
  # Maven dependencies
  - package-ecosystem: "maven"
    directory: "/src/sonar-hooks"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "movares-team"
    assignees:
      - "movares-team"
    commit-message:
      prefix: "build(deps):"
      include: "scope"
    groups:
      sonarqube:
        patterns:
          - "org.sonarsource.*"
      test-dependencies:
        patterns:
          - "org.junit.*"
          - "org.mockito*"
          - "org.assertj*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "movares-team"
    assignees:
      - "movares-team"
    commit-message:
      prefix: "ci:"
      include: "scope" 